name: jastar_hub_community
description: "Jastar Hub Community — Cross-Platform Event Community App with AI Recommendations"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^14.8.0

  # Network
  dio: ^5.7.0

  # WebSocket
  socket_io_client: ^3.0.2

  # Local Storage
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.2.4

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  # Utils
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  timeago: ^3.7.0
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
